### ISSUE TITLE
Add a license to the repository if applicable

### ISSUE THREAD

**Issue by LavenderTheGreat** [Breadkenty/Smash_Combos#2]
Github automatically picks up file creations from within git labelled LICENSE or LICENSE.MD and brings up an interface allowing more detailed creation of a licence with upsides and downsides. Not having a licence can create problems for people looking to use the software as seen [here](https://choosealicense.com/no-permission/). [Choose A License](https://choosealicense.com/) is also a good site by Github for simplifying the licensing process.

**Comment by Breadkenty** [comment]
Added the MIT license. Thanks!
