### ISSUE TITLE
Create/Update Models for Moderation

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/Smash_Combos#21]
We're updating the models to implement the moderation feature. I only have a few concerns about this model and if you see any problems please post them here. One primary issue is having two foreign keys for `UserId` labeled as `UserId` and `Reporter/ModeratorId`. Please check out the UI to see how this will be implemented in #15 

**Update User Model**
- [ ] Add `int UserStatus = 1`. This model will be responsible for determining the rank of the user. 3 for admin, 2 for mods, 1 for users. Make this property private.
- [ ] Add `List<Combo>Combos`. This will allow the UI to see the `user page` with all of their reports for a Combo.
- [ ] Add `List<Comments>Comments`. This will allow the UI to see the `user page` with all of their reports for a comment
- [ ] Add `List<Infraction>Infraction`. This will allow the UI to see the `user page` with their infractions

**Update Combo Model**
- [ ] Add `List<Report>Reports`. People will report combos

**Update Comment Model*
- [ ] Add `List<Report>Reports`. People will report comments

**Create Report Model**
- [ ] `int Id`
- [ ] `int UserId` (The id of the user being reported)
- [ ] `int ReporterId` (The id of the creating the report)
- [ ] `string Body`[required]
- [ ] `DateTime DateReported = DateTime.Now()` (make this private)
- [ ] `bool Dismiss = false`

**Create Infraction Model**
- [ ] `int Id`
- [ ] `int UserId` (The id of the user being infracted)
- [ ] `int ModeratorId` (The id of the user/moderator giving the infraction)
- [ ] `int banDuration = 0`(this int will be in seconds)
- [ ] `type`[required]
- [ ] `int Points = 0` (make this private)
- [ ] `string body`[required]
- [ ] `DateTime DateInfracted = DateTime.Now()` (make this private)

---

- [ ] Create Migrations
- [ ] Test to make sure the two `UserId` and `Reporter/ModeratorId` in the `Report` and `Infraction` model works as foreign keys.

**Comment by sleeping-dev** [comment]
I think holding the banDuration as an int (seconds) would be nicer, together with DateInfracted we could always get the exact end-date of a ban by adding the seconds to the DateInfracted date (a method the DateTime class provides)

So when we handle a user login we could check if they have any infractions where this calculated date is still in the future - > ergo they're still banned.

**Comment by Breadkenty** [comment]
I definitely like that approach better, I'll fix it on the issue here. Thanks!

**Comment by sleeping-dev** [comment]
One issue that we would need to think about is indefinite bans, since we cant represent those this way... (unless we just set the ban duration to int.MaxValue, but that doesn't seem too clean) Just thought of this, any ideas for that?

**Comment by skittlz444** [comment]
I don't think you could have combo and comment id on report. You'll be able to access the report from the combo or comment respectively. This will stop the report object from getting unnecessarily bloated with ids.

**Comment by Breadkenty** [comment]
Yeah I was starting to feel that these models are looking messy with IDs that way. I'll remove it here. I wonder if we can just set the perma-bans to something unnecessarily long?

**Comment by sleeping-dev** [comment]
We could set them to int.MaxValue and check for that, longer is impossible unless we change the data type, but that would work too.

**Comment by sleeping-dev** [comment]
Anyway, I'll get started on this now and have a pull request up soon for review.
