### ISSUE TITLE
Create/Update Controllers

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/Smash_Combos#23]
- [ ] `.Include` `Reports` lists from the `User` model in the `GET` controller. We should be able to access all the reports of their comments and combos of a user when we fetch the user's ApiData.
- [ ] a POST on the report should handle the `null` of either comments or combos. This will allow us to use one report table for both `Comment` and `Combo`
**a POST on the infract should handle both bans and warnings.**
- [ ] As a warning, the points should be determined by the `type`. 
- [ ] As a ban, the `banDuration` will be determined by the JSON object passed in seconds.

**Note: I didn't include this in the UI mock-up, but when banning a user, there should also be a button to choose the `type` along with `banDuration`**

- [ ] The report should come in this JSON format. Make sure this is valid.
{
  userId: Id of the user being reported,
  reporterId: Id of the user reporting,
  comboId: Id of the combo that was reported (if reported on a comment, this will be null),
  commentId: Id of the comment that was reported (if reported on a combo, this will be null),
  body: "THIS COMBO WAS UNCALLED FOR!",
}

- [ ] The infraction should come in this JSON format. Make sure this is valid.
#### a user getting banned
```
{
  userId: Id of the user being infracted,
  moderatorId: Id of the moderator infracting,
  banDuration: 172800,
  type: "inappropriate",
  body: "Inappropriate post for PK Blazing Butthole",
}
```

`banDuration`
2 Days = 172800s
1 Week = 604800s
2 weeks = 1209600s
1 month = 2419200s
Permanent = infinite

#### a user getting warned
```
{
  userId: Id of the user being infracted,
  moderatorId: Id of the moderator infracting,
  banDuration: null;
  type: "spam",
  body: "Spamming the same combos",
}
```

Looking to expand this list. thinking about removing other so mods will not be able to abuse the point system.
`spam` = `1` point
`inappropriate` = `1` point
`harassment` = `2` points
`other` = `custom?` points

**Comment by sleeping-dev** [comment]
Do we need isBan? If I see it correctly isBan is always true when there's a banDuration, so when the banDuration is null we can assume that the user didn't get banned,and if there is one we know that they were.

**Comment by Breadkenty** [comment]
Updated!

**Comment by skittlz444** [comment]
Since reports are essentially sub entities of combos and comments, there may have to be two separate POSTs to the api. One for `/Comment/{comment Id}/Report` and similar for combo.

**Comment by sleeping-dev** [comment]
I'm gonna start working on moving the logic from the ApiControllers to Core. I'll split the pull requests up for each controller for cleanliness.
