### ISSUE TITLE
Fix scrolling on the sign on page

### ISSUE THREAD

**Issue by skittlz444** [Breadkenty/Smash_Combos#33]
Reported by TriAttack. Sunday, September 13th, 10:24(AEST).

I cannot scroll up from this. Some sort of front-end error.
![unknown.png](https://user-images.githubusercontent.com/12255389/93007918-dcc2ec80-f5b1-11ea-8f51-df3c0f6b9d36.png)

Device: Chrome
Resolution: 1920x1080

**Comment by Breadkenty** [comment]
Fixed e8220e8d1a665e7dc8b911624e682a3f9f547e6b
