### ISSUE TITLE
Fix scrolling on the combo page 

### ISSUE THREAD

**Issue by skittlz444** [Breadkenty/Smash_Combos#34]
Reported by KuraiTenshi, Sunday 13th September, 10:39am(AEST).

Is this the intended behaviour of a combo page? I'm trying to scroll down but the combo remains at the top, making the rest of the page hard to see
![VnFLAL1.png](https://user-images.githubusercontent.com/12255389/93007951-62df3300-f5b2-11ea-99a5-d76ebb5e57ef.png)

the combo is here if anyone else wants to see the page behaviour https://smash-combos-dev.herokuapp.com/character/LittleMac/10
it scrolls like this on firefox and chrome too

**Comment by sleeping-dev** [comment]
I've talked about this with @Breadkenty before, it's a side effect from the page being built for mobile devices. We'll look into making it easier to look at from desktop computers (probably just make the video scroll up and not stick to the top)

**Comment by Breadkenty** [comment]
Fixed in 8b90904f31a1e25027630b4e31ab29beccf04080
