### ISSUE TITLE
Separate Mii and Pokemon Trainer into individual characters

### ISSUE THREAD

**Issue by Breadkenty** [Breadkenty/Smash_Combos#4]
Characters that are merged need to be separated. In order to do this, we would need to implement a way to put the characters in order so when adding them to the code, please follow the format on the [official Smash Bros site](https://www.smashbros.com/en_US/fighter/index.html)

- [ ] Create graphics for individual characters.
- [ ] When importing graphics, keep the name consistent with other character structure with their own `variableNames`. 
- [ ] Add characters to `allCharacterCloseUp.jsx`, `allCharacterPortrait.jsx`, and `characters.sql`
- [ ] Update character model to include `releaseOrder` to put the character in order
- [ ] Update migrations

**Comment by ejbee3** [comment]
I am working on this now! Was wondering how you want pokemon trainer in the character list? For the mii fighters I was just going to add all three, but pokemon trainer is a little different in that the image of pokemon trainer is separate from squirtle, ivysaur, and charizard.

**Comment by sleeping-dev** [comment]
Does pokemon trainer even need to be in the list anymore? I don't think there are any combos or strings that reliably work inbetween pokemon switches, so it might be fine just having the pokemon separate.

**Comment by ejbee3** [comment]
Oh I just meant for the sake of the character list it could be nice to click on the pokemon trainer image and then choose between the three depending on which combo list you want to see/add combo to.

**Comment by sleeping-dev** [comment]
Oh I see! I don't know _how_ much more useful that would be, since if we order them according to [the smash bros site](https://www.smashbros.com/en_US/fighter/index.html) they're gonna be right next to each other anyway, but it could be a neat feature.

**Comment by ejbee3** [comment]
I gotcha. Yeah I'll just leave it showing all three for now and just keep the PT image in case somebody wants to add that later.

**Comment by ejbee3** [comment]
It's fine this time @sleeping-dev but please comment that you're working on this in the future; I was almost finished with my commit! I like your sort function, though 😄

**Comment by sleeping-dev** [comment]
I definitely will! Sorry again and thanks! 😄
